- Stage1_h.py
- Stage2.py
- mafft_and_phylip.py
- test_crispys.py
The polymorphic site argument was hardcoded internaly.
I changed it to be the user input argument - PS_number.
I have also changed the need for using perl.
Now the change from fasta to phylip format is done with Bio.SeqIO.parse
> Crispys udi local

- CasSites.py
- Stage0.py
- Stage1_h.py
- Stage2.py
- Stage3.py
- UPGMA.py
changed the number of nucleotides in each target. this change does not apply when using cfd/ccTop/MITscore as scoring functions
> changed the number of nucleotides in the target to 23

- Stage1_h.py
- globals.py
This commit has the new 'N_genes_in_node' variable
> add global variables

- test_crispys.py
Add option to compare with server output
> add an option to compare with server results

- Distance_matrix_and_UPGMA.py
- Metric.py
- Stage2.py
- Stage3.py
- globals.py
- changed the distance transformation so each target will be transformed into a vector of length number of targets (in Metric.pos_in_metric_general/_single_batch).
- commented out the infamous "if cut_expection >= 1:" in Stage3.return_candidates line 110 since it has no purpose and doesn't work well with scoring functions where the score of a perfect match is lower than 1.
- make initial matrix will now always take a list of vectors as input.
- changed the defult number of n_cores_for_gold_off from 1 to 10
> Fixed the distance transformation

- CasSites.py
- Stage3.py
- run_local.py
- test_crispys.py
Fixed error done with conflicts and update test
> Crispys udi 

- Distance_matrix_and_UPGMA.py
- globals.py
gold off will now use the regression model "union_log_max.xgb" rather than the classification model
> Changed the gold off model to regression

- Metric.py
pos_in_metric_general will only create the list of metric sequences if the scoring is not CFD.
> Moved "list of metric sequences" down the script

- Metric.py
- test_crispys.py
> Crispys udi

- CRISPR_Net/CRISPR_Net.py
- CRISPR_Net/CRISPR_Net_Aggregate.py
- CrisprNetLoad.py
- Stage0.py
- crispys.yml
- globals.py
- server_run.py
changes elaborated in the commits
> Yossi updates

- Stage0.py
- Stage1.py
- globals.py
- make_tree_display_CSV.py
results of algorithm run changed to list of SubgroupRes objects for default run as well
> SubgroupRes results

- Stage0.py
- Stage1.py
- Stage3.py
- crispys.yml
- globals.py
slim_output argument in main function accepts a boolean. False by default, True for slim outpu, which is only 'res_in_lst' file
> Slim output option added

- MOFF/MoffLoad.py
Added full path to  models.load_model in MoffLoad.py
> #100 Commit!

- Stage3.py
It is relevant for cases where omega is set to 0.
> Added an extra condition in Stage3.py.

- gold_off.py
This allows for faster and easier debugging.
> gold_off.py will no longer use multi-processing when n_cores is set to 1

- TreeConstruction_changed.py
- globals.py
- gold_off.py
- Added a "parent" attribute to the CladeNew object. The attribute points to its direct parental CladeNew object (or none if the clade is the root).
- Added back the n_jobs=n_process in gold_off.py
> Parent update:

- Stage0.py
- Stage1.py
- Stage2.py
- Stage3.py
- SubgroupRes.py
- run_crispys_on_families.py
- test_crispys.py
- Added a "family_name" attribute to SubgroupRes.py
- Added a function "add_family_name" to Stage0.py which adds the family name to each SubgroupRes object
- Renames "singletons" to "singletons_from_crispys" on all function
- Added three new parameters that will be used for the future singletons implementation
- Fixed a bug in Stage1.py causing the output to be empty when singletons_from_crispys was set to 1
> Family name changes:

- Stage1.py
Fixed a typo in Stage1.py causing the program to not work when looking at a gene with no targets
> Small bugfix

- CasSites.py
- Stage0.py
- Stage1.py
- run_crispys_on_families.py
- singletons.py
- Added new script that finds singletons for genes in the list of interest.
> Singletons patch:

- Stage0.py
- Stage1.py
- run_crispys_on_families.py
- server_run.py
- test_crispys.py
Renamed "desired_genes_fraction_threshold" to "min_desired_genes_fraction" and improved its documentation
> min_desired_genes_fraction
